[password]
secret_key = "3wT7Kf8JmLq1Zx9Pn2GtHv6YvBcDdRt5"

[database]
url = "postgres://postgres:password@localhost:5432/matchmaker?sslmode=disable"
max_conn = 1000

[http]
host = "localhost"
port = 8080

