services:
  postgres:
    image: postgres:latest
    container_name: matchmaker-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: matchmaker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - common-network

networks:
  common-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local